modLoader = "javafml" #mandatory
loaderVersion = "[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "mit"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId = "taratech" #mandatory
version = "0.1" #mandatory
displayName = "TaraTech" #mandatory
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
#logoFile="taratech.png" #optional
credits="Credits go to the amazing Development Team that made this mod!" #optional
authors = "TaraTech Development Team" #optional
description = '''
Technology mod with some chemistry
''' #Mandatory
[[dependencies.taratech]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[31,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.taratech]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2,1.16)"
ordering = "NONE"
side = "BOTH"
